version: "2"
services:
  node:
    container_name: node
    build: .
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOSTNAME=mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"